const express = require('express');
const router = express.Router();
const { getPricePrediction, getSellRecommendation, calculateProfit, getDemandForecast, getCropRecommendation } = require('../controllers/recommendationController');
const { protect } = require('../middlewares/authMiddleware');
router.post('/predict', protect, getPricePrediction);
router.post('/smart-sell', protect, getSellRecommendation);
router.post('/profit-calculator', protect, calculateProfit);
router.get('/demand-forecast', protect, getDemandForecast);
router.post('/crop-recommendation', protect, getCropRecommendation);
module.exports = router;
